repos:
  - repo: local
    hooks:
      - id: playwright-tests
        name: Playwright UI Tests
        entry: bash -c 'cd /Users/noelmcmichael/Workspace/senate_hearing_audio_capture && node run-tests.js'
        language: system
        stages: [commit]
        pass_filenames: false
        verbose: true
        
  - repo: local
    hooks:
      - id: quick-system-check
        name: Quick System Check
        entry: bash -c 'cd /Users/noelmcmichael/Workspace/senate_hearing_audio_capture && node quick-system-check.js'
        language: system
        stages: [push]
        pass_filenames: false
        verbose: true
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']