# Prometheus configuration for Senate Hearing Audio Capture
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'senate-hearing-monitor'

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'senate-hearing-app'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 30s
    
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 30s
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093